### ISSUE TITLE
Running in kraken

### ISSUE THREAD

**Issue by jjuarez84** [ggutierrez-bio/ligbinder#6]
The environment does not seem to be properly set up to run ligbinder in kraken. Following the instructions in the repo leads to: 

/var/spool/slurm/d/job21835/slurm_script: line 9: ligbinder: command not found

**Comment by ggutierrez-bio** [comment]
I installed an 'official version' in kraken, and created the module for it.
Also, I updated the kraken template. please give it another try.

**Comment by jjuarez84** [comment]
It looks like is working now!
👍🏻
