### ISSUE TITLE
Results are not correctly handled when ligand binds

### ISSUE THREAD

**Issue by jjuarez84** [ggutierrez-bio/ligbinder#9]
results folder is empty when a simulation converges to a bound structure. Attached is the python traceback that is dumped to the standard output/error file:

[ligbinder.python.log](https://github.com/ggutierrez-bio/ligbinder/files/6188296/ligbinder.python.log)

**Comment by ggutierrez-bio** [comment]
reporting bugs have been fixed.
also, biasing power has been redefined to take into account the total number of leaves for each branch.
please install again in portal and give it a try.
if everything works fine I'll merge the fix to master
